version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api  

  api:
    build:
      context: ./src/api
    ports:
      - "3000:3000"  
    # volumes:
    #   - ./src/api:/usr/src/app
    environment:
      NODE_ENV: development

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: bruno
      RABBITMQ_DEFAULT_PASS: bruno
